baseURL: "http://blog.xdean.cn/"
theme: "maupassant"
languageCode: "zh-CN"
title: "XDean的博客"
taxonomies:
  tag: "tags"
  category: "categories"
author:
  name: "XDean"
params:
  author: "XDean"
  subtitle: ""
  keywords: ""
  description: ""
  utteranc:
    enable: true
    repo: "XDean/blog-comment"
    issueTerm: "url"
    theme: "github-light"
  busuanzi: true
  cc:
    name: "CC BY-SA 4.0"
    link: "https://creativecommons.org/licenses/by-sa/4.0/deed.zh"
menu:
  main:
    - identifier: "archives"
      name: "归档"
      url: "/archives/"
      weight: 2
    - identifier: "about"
      name: "关于"
      url: "/about/"
      weight: 3
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: title
      weight: 50
    - name: categories
      weight: 50
    - name: tegs
      weight: 50
    - name: date
      weight: 10
disablePathToLower: true
googleAnalytics: "UA-145930182-1"